version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host  
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost  
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=jobkeep

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: jobkeep
